-- Generated by scripts/generate-postgres-schema.ts.
SELECT pg_advisory_xact_lock(7268842401162020);

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS campaigns (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      role_name TEXT NOT NULL,
      status TEXT NOT NULL,
      owner_name TEXT NOT NULL,
      business_goal TEXT NOT NULL,
      value_proposition TEXT NOT NULL,
      locations_json JSONB NOT NULL,
      markets_json JSONB NOT NULL,
      channels_json JSONB NOT NULL,
      must_haves_json JSONB NOT NULL,
      nice_to_haves_json JSONB NOT NULL,
      exclusions_json JSONB NOT NULL,
      target_organization_count INTEGER NOT NULL,
      target_person_count INTEGER NOT NULL,
      weekly_target INTEGER NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS organizations (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      normalized_name TEXT NOT NULL,
      domain TEXT NOT NULL,
      location TEXT NOT NULL,
      size TEXT NOT NULL,
      description TEXT NOT NULL,
      identity_confidence REAL NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      UNIQUE(normalized_name, domain)
    );

CREATE TABLE IF NOT EXISTS campaign_organizations (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      organization_id TEXT NOT NULL,
      category TEXT NOT NULL,
      status TEXT NOT NULL,
      products_json JSONB NOT NULL,
      markets_json JSONB NOT NULL,
      channels_json JSONB NOT NULL,
      monetization_json JSONB NOT NULL,
      business_history_json JSONB NOT NULL DEFAULT '[]',
      current_business_json JSONB NOT NULL DEFAULT '[]',
      business_status TEXT NOT NULL DEFAULT 'UNKNOWN',
      business_status_summary TEXT NOT NULL DEFAULT '',
      business_signals_json JSONB NOT NULL DEFAULT '[]',
      business_status_confidence INTEGER NOT NULL DEFAULT 0,
      fit_score INTEGER NOT NULL,
      evidence_coverage INTEGER NOT NULL,
      confidence INTEGER NOT NULL,
      evidence_source_count INTEGER NOT NULL DEFAULT 0,
      source_quality_score INTEGER NOT NULL DEFAULT 0,
      recommendation_reason TEXT NOT NULL,
      unknowns_json JSONB NOT NULL,
      owner_name TEXT NOT NULL,
      review_reason TEXT NOT NULL DEFAULT '',
      updated_at TIMESTAMPTZ NOT NULL,
      UNIQUE(campaign_id, organization_id)
    );

CREATE TABLE IF NOT EXISTS people (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      normalized_name TEXT NOT NULL,
      headline TEXT NOT NULL,
      location TEXT NOT NULL,
      identity_confidence REAL NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS campaign_people (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      person_id TEXT NOT NULL,
      organization_id TEXT NOT NULL,
      slot TEXT NOT NULL,
      status TEXT NOT NULL,
      fit_score INTEGER NOT NULL,
      evidence_coverage INTEGER NOT NULL,
      identity_confidence INTEGER NOT NULL,
      recommendation_reason TEXT NOT NULL,
      strengths_json JSONB NOT NULL,
      unknowns_json JSONB NOT NULL,
      risk_flags_json JSONB NOT NULL,
      owner_name TEXT NOT NULL,
      review_reason TEXT NOT NULL DEFAULT '',
      last_interaction_at TIMESTAMPTZ,
      updated_at TIMESTAMPTZ NOT NULL,
      UNIQUE(campaign_id, person_id)
    );

CREATE TABLE IF NOT EXISTS evidence (
      id TEXT PRIMARY KEY,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      classification TEXT NOT NULL,
      claim_text TEXT NOT NULL,
      quote TEXT NOT NULL,
      source_title TEXT NOT NULL,
      source_url TEXT NOT NULL,
      source_provider TEXT NOT NULL,
      confidence REAL NOT NULL,
      observed_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS tasks (
      id TEXT PRIMARY KEY,
      campaign_id TEXT,
      type TEXT NOT NULL,
      status TEXT NOT NULL,
      title TEXT NOT NULL,
      result_summary TEXT NOT NULL,
      payload_json JSONB NOT NULL,
      steps_json JSONB NOT NULL,
      attempts INTEGER NOT NULL DEFAULT 0,
      max_attempts INTEGER NOT NULL DEFAULT 3,
      model_name TEXT NOT NULL,
      estimated_cost REAL NOT NULL DEFAULT 0,
      idempotency_key TEXT UNIQUE,
      created_at TIMESTAMPTZ NOT NULL,
      completed_at TIMESTAMPTZ
    );

CREATE TABLE IF NOT EXISTS sources (
      id TEXT PRIMARY KEY,
      campaign_id TEXT,
      provider TEXT NOT NULL,
      title TEXT NOT NULL,
      source_type TEXT NOT NULL,
      source_url TEXT NOT NULL,
      content_hash TEXT NOT NULL,
      extracted_text TEXT NOT NULL,
      imported_count INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL,
      UNIQUE(provider, content_hash)
    );

CREATE TABLE IF NOT EXISTS feedback (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      action TEXT NOT NULL,
      reason_code TEXT NOT NULL,
      note TEXT NOT NULL,
      operator_name TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS profile_versions (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      version INTEGER NOT NULL,
      criteria_json JSONB NOT NULL,
      is_active INTEGER NOT NULL DEFAULT 1,
      created_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      UNIQUE(campaign_id, version)
    );

CREATE TABLE IF NOT EXISTS resume_documents (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      person_id TEXT,
      file_name TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      source_type TEXT NOT NULL,
      legal_basis TEXT NOT NULL,
      storage_path TEXT NOT NULL,
      content_hash TEXT NOT NULL,
      extracted_text TEXT NOT NULL,
      status TEXT NOT NULL,
      quality_score INTEGER NOT NULL DEFAULT 0,
      quality_grade TEXT NOT NULL DEFAULT 'UNASSESSED',
      quality_reasons_json JSONB NOT NULL DEFAULT '[]',
      quality_metrics_json JSONB NOT NULL DEFAULT '{}',
      graph_eligible INTEGER NOT NULL DEFAULT 0,
      search_eligible INTEGER NOT NULL DEFAULT 0,
      quality_assessed_at TIMESTAMPTZ,
      parse_version TEXT NOT NULL DEFAULT '',
      error_message TEXT NOT NULL DEFAULT '',
      retention_until TIMESTAMPTZ,
      created_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL,
      analyzed_at TIMESTAMPTZ, source_search_task_id TEXT, source_strategy_version_id UUID, experiment_assignment_id UUID,
      UNIQUE(campaign_id, content_hash)
    );

CREATE TABLE IF NOT EXISTS resume_identity_matches (
      resume_id TEXT PRIMARY KEY,
      person_id TEXT,
      matched_person_id TEXT,
      decision TEXT NOT NULL,
      score REAL NOT NULL,
      confidence REAL NOT NULL,
      reasons_json JSONB NOT NULL,
      candidate_count INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS employments (
      id TEXT PRIMARY KEY,
      person_id TEXT NOT NULL,
      organization_id TEXT NOT NULL,
      resume_id TEXT NOT NULL,
      sequence INTEGER NOT NULL,
      raw_company_name TEXT NOT NULL,
      raw_title TEXT NOT NULL,
      normalized_role TEXT NOT NULL,
      start_date TEXT,
      end_date TEXT,
      is_current INTEGER NOT NULL DEFAULT 0,
      summary TEXT NOT NULL,
      confidence REAL NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      UNIQUE(resume_id, sequence)
    );

CREATE TABLE IF NOT EXISTS skills (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      normalized_name TEXT NOT NULL UNIQUE,
      category TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS person_skills (
      id TEXT PRIMARY KEY,
      person_id TEXT NOT NULL,
      skill_id TEXT NOT NULL,
      resume_id TEXT NOT NULL,
      confidence REAL NOT NULL,
      evidence_text TEXT NOT NULL,
      last_seen_at TIMESTAMPTZ NOT NULL,
      UNIQUE(person_id, skill_id, resume_id)
    );

CREATE TABLE IF NOT EXISTS organization_facts (
      id TEXT PRIMARY KEY,
      organization_id TEXT NOT NULL,
      field_name TEXT NOT NULL,
      value_json JSONB NOT NULL,
      confidence REAL NOT NULL,
      source_resume_id TEXT,
      status TEXT NOT NULL,
      classification TEXT NOT NULL DEFAULT 'FACT',
      evidence_quote TEXT NOT NULL DEFAULT '',
      source_quality_score INTEGER NOT NULL DEFAULT 0,
      first_seen_at TIMESTAMPTZ NOT NULL,
      last_seen_at TIMESTAMPTZ NOT NULL,
      UNIQUE(organization_id, field_name, value_json, source_resume_id)
    );

CREATE TABLE IF NOT EXISTS graph_edges (
      id TEXT PRIMARY KEY,
      from_type TEXT NOT NULL,
      from_id TEXT NOT NULL,
      edge_type TEXT NOT NULL,
      to_type TEXT NOT NULL,
      to_id TEXT NOT NULL,
      weight REAL NOT NULL,
      confidence REAL NOT NULL,
      source_resume_id TEXT,
      first_seen_at TIMESTAMPTZ NOT NULL,
      last_seen_at TIMESTAMPTZ NOT NULL,
      UNIQUE(from_type, from_id, edge_type, to_type, to_id, source_resume_id)
    );

CREATE TABLE IF NOT EXISTS ai_settings (
      setting_key TEXT PRIMARY KEY,
      setting_value TEXT NOT NULL,
      is_secret INTEGER NOT NULL DEFAULT 0,
      updated_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS ai_runs (
      id TEXT PRIMARY KEY,
      campaign_id TEXT,
      run_type TEXT NOT NULL,
      business_date TEXT,
      status TEXT NOT NULL,
      stage TEXT NOT NULL,
      scope_json JSONB NOT NULL,
      profile_snapshot_json JSONB NOT NULL,
      input_watermark TEXT,
      output_watermark TEXT,
      summary TEXT NOT NULL,
      metrics_json JSONB NOT NULL,
      error_message TEXT NOT NULL DEFAULT '',
      triggered_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ
    );

CREATE TABLE IF NOT EXISTS ai_run_items (
      id TEXT PRIMARY KEY,
      run_id TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      status TEXT NOT NULL,
      attempts INTEGER NOT NULL DEFAULT 0,
      result_json JSONB NOT NULL,
      error_message TEXT NOT NULL DEFAULT '',
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      UNIQUE(run_id, entity_type, entity_id)
    );

CREATE TABLE IF NOT EXISTS search_tasks (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      run_id TEXT,
      task_type TEXT NOT NULL,
      title TEXT NOT NULL,
      company_name TEXT NOT NULL,
      query_json JSONB NOT NULL,
      reason_json JSONB NOT NULL,
      priority INTEGER NOT NULL,
      dedupe_key TEXT NOT NULL UNIQUE,
      status TEXT NOT NULL,
      claimed_by TEXT,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      completed_at TIMESTAMPTZ
    , strategy_version_id UUID, experiment_assignment_id UUID);

CREATE TABLE IF NOT EXISTS search_task_feedback (
      id TEXT PRIMARY KEY,
      task_id TEXT NOT NULL,
      result_count INTEGER NOT NULL,
      qualified_count INTEGER NOT NULL,
      effective_conversations INTEGER NOT NULL,
      note TEXT NOT NULL,
      created_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS learning_weights (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      signal_type TEXT NOT NULL,
      signal_key TEXT NOT NULL,
      sample_count INTEGER NOT NULL,
      positive_count REAL NOT NULL,
      weight REAL NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL,
      UNIQUE(campaign_id, signal_type, signal_key)
    );

CREATE TABLE IF NOT EXISTS learning_recommendations (
      id TEXT PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      run_id TEXT,
      recommendation_type TEXT NOT NULL,
      title TEXT NOT NULL,
      reason TEXT NOT NULL,
      payload_json JSONB NOT NULL,
      confidence REAL NOT NULL,
      status TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      reviewed_at TIMESTAMPTZ
    );

CREATE TABLE IF NOT EXISTS plugin_sessions (
      id TEXT PRIMARY KEY,
      email TEXT NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      expires_at TIMESTAMPTZ NOT NULL,
      last_seen_at TIMESTAMPTZ NOT NULL,
      revoked_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email CITEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'ACTIVE',
      must_change_password INTEGER NOT NULL DEFAULT 0,
      last_login_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS roles (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      code CITEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '',
      is_system INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS permissions (
      code TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      group_name TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      sort_order INTEGER NOT NULL DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS user_roles (
      user_id TEXT NOT NULL,
      role_id TEXT NOT NULL,
      PRIMARY KEY (user_id, role_id)
    );

CREATE TABLE IF NOT EXISTS role_permissions (
      role_id TEXT NOT NULL,
      permission_code TEXT NOT NULL,
      PRIMARY KEY (role_id, permission_code)
    );

CREATE TABLE IF NOT EXISTS web_sessions (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      expires_at TIMESTAMPTZ NOT NULL,
      last_seen_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS strategy_versions (
      id UUID PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      version INTEGER NOT NULL,
      status TEXT NOT NULL,
      parent_version_id UUID,
      source_review_run_id UUID,
      strategy_json JSONB NOT NULL,
      change_summary TEXT NOT NULL,
      created_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      activated_at TIMESTAMPTZ,
      superseded_at TIMESTAMPTZ,
      UNIQUE(campaign_id, version)
    );

CREATE TABLE IF NOT EXISTS experiments (
      id UUID PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      strategy_version_id UUID,
      name TEXT NOT NULL,
      dimension TEXT NOT NULL,
      status TEXT NOT NULL,
      primary_metric TEXT NOT NULL,
      allocation_percent INTEGER NOT NULL DEFAULT 20,
      minimum_tasks INTEGER NOT NULL DEFAULT 5,
      minimum_results INTEGER NOT NULL DEFAULT 30,
      arms_json JSONB NOT NULL,
      result_json JSONB NOT NULL DEFAULT '{}',
      created_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ
    );

CREATE TABLE IF NOT EXISTS experiment_assignments (
      id UUID PRIMARY KEY,
      experiment_id UUID NOT NULL,
      arm_key TEXT NOT NULL,
      search_task_id TEXT,
      person_id TEXT,
      assigned_at TIMESTAMPTZ NOT NULL,
      UNIQUE(experiment_id, search_task_id, person_id)
    );

CREATE TABLE IF NOT EXISTS review_runs (
      id UUID PRIMARY KEY,
      campaign_id TEXT,
      review_type TEXT NOT NULL,
      status TEXT NOT NULL,
      window_start TIMESTAMPTZ NOT NULL,
      window_end TIMESTAMPTZ NOT NULL,
      metrics_json JSONB NOT NULL,
      diagnosis_json JSONB NOT NULL,
      proposed_changes_json JSONB NOT NULL,
      applied_changes_json JSONB NOT NULL,
      confidence REAL NOT NULL DEFAULT 0,
      model_name TEXT NOT NULL,
      estimated_cost REAL NOT NULL DEFAULT 0,
      error_message TEXT NOT NULL DEFAULT '',
      triggered_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      completed_at TIMESTAMPTZ
    );

CREATE TABLE IF NOT EXISTS intelligence_sources (
      id UUID PRIMARY KEY,
      organization_id TEXT,
      source_type TEXT NOT NULL,
      trust_tier TEXT NOT NULL,
      title TEXT NOT NULL,
      url TEXT NOT NULL,
      publisher TEXT NOT NULL,
      published_at TIMESTAMPTZ,
      quote TEXT NOT NULL,
      content_hash TEXT NOT NULL,
      collected_at TIMESTAMPTZ NOT NULL,
      UNIQUE(url, content_hash)
    );

CREATE TABLE IF NOT EXISTS evidence_claims (
      id UUID PRIMARY KEY,
      organization_id TEXT,
      subject_type TEXT NOT NULL,
      subject_id TEXT NOT NULL,
      claim_type TEXT NOT NULL,
      classification TEXT NOT NULL,
      statement TEXT NOT NULL,
      value_json JSONB NOT NULL,
      confidence INTEGER NOT NULL,
      status TEXT NOT NULL,
      valid_from TIMESTAMPTZ,
      valid_until TIMESTAMPTZ,
      first_seen_at TIMESTAMPTZ NOT NULL,
      last_seen_at TIMESTAMPTZ NOT NULL,
      conflict_group_key TEXT NOT NULL DEFAULT '',
      UNIQUE(subject_type, subject_id, claim_type, statement)
    );

CREATE TABLE IF NOT EXISTS claim_sources (
      claim_id UUID NOT NULL,
      source_id UUID NOT NULL,
      PRIMARY KEY (claim_id, source_id)
    );

CREATE TABLE IF NOT EXISTS business_units (
      id UUID PRIMARY KEY,
      organization_id TEXT NOT NULL,
      name TEXT NOT NULL,
      unit_type TEXT NOT NULL,
      description TEXT NOT NULL,
      status TEXT NOT NULL,
      confidence INTEGER NOT NULL,
      valid_from TIMESTAMPTZ,
      valid_until TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL,
      UNIQUE(organization_id, name)
    );

CREATE TABLE IF NOT EXISTS projects (
      id UUID PRIMARY KEY,
      organization_id TEXT NOT NULL,
      business_unit_id UUID,
      name TEXT NOT NULL,
      project_type TEXT NOT NULL,
      status TEXT NOT NULL,
      region TEXT NOT NULL,
      client_name TEXT NOT NULL,
      products_json JSONB NOT NULL,
      skills_json JSONB NOT NULL,
      summary TEXT NOT NULL,
      confidence INTEGER NOT NULL,
      talent_demand_confidence INTEGER NOT NULL DEFAULT 0,
      started_at TIMESTAMPTZ,
      ended_at TIMESTAMPTZ,
      valid_until TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL,
      UNIQUE(organization_id, name, project_type)
    );

CREATE TABLE IF NOT EXISTS project_claims (
      project_id UUID NOT NULL,
      claim_id UUID NOT NULL,
      PRIMARY KEY (project_id, claim_id)
    );

CREATE TABLE IF NOT EXISTS organization_events (
      id UUID PRIMARY KEY,
      organization_id TEXT NOT NULL,
      event_type TEXT NOT NULL,
      title TEXT NOT NULL,
      summary TEXT NOT NULL,
      classification TEXT NOT NULL,
      confidence INTEGER NOT NULL,
      occurred_at TIMESTAMPTZ,
      valid_until TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE TABLE IF NOT EXISTS research_tasks (
      id UUID PRIMARY KEY,
      campaign_id TEXT,
      organization_id TEXT,
      topic TEXT NOT NULL,
      trigger_type TEXT NOT NULL,
      status TEXT NOT NULL,
      result_summary TEXT NOT NULL DEFAULT '',
      error_message TEXT NOT NULL DEFAULT '',
      attempts INTEGER NOT NULL DEFAULT 0,
      model_name TEXT NOT NULL DEFAULT '',
      created_by TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      dedupe_key TEXT NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS activity_events (
      id UUID PRIMARY KEY,
      campaign_id TEXT,
      person_id TEXT,
      organization_id TEXT,
      resume_id TEXT,
      search_task_id TEXT,
      strategy_version_id UUID,
      experiment_assignment_id UUID,
      event_type TEXT NOT NULL,
      from_status TEXT,
      to_status TEXT,
      reason_code TEXT NOT NULL,
      actor_type TEXT NOT NULL,
      actor_id TEXT NOT NULL,
      payload_json JSONB NOT NULL,
      occurred_at TIMESTAMPTZ NOT NULL,
      idempotency_key TEXT NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS candidate_origins (
      id UUID PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      person_id TEXT NOT NULL,
      resume_id TEXT,
      search_task_id TEXT,
      organization_id TEXT,
      strategy_version_id UUID,
      experiment_assignment_id UUID,
      keyword_json JSONB NOT NULL,
      source_type TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      dedupe_key TEXT NOT NULL UNIQUE,
      UNIQUE(campaign_id, person_id, resume_id, search_task_id)
    );

CREATE TABLE IF NOT EXISTS analytics_snapshots (
      id UUID PRIMARY KEY,
      campaign_id TEXT NOT NULL,
      business_date TEXT NOT NULL,
      window_days INTEGER NOT NULL,
      metrics_json JSONB NOT NULL,
      dimensions_json JSONB NOT NULL,
      data_quality_json JSONB NOT NULL,
      created_at TIMESTAMPTZ NOT NULL,
      UNIQUE(campaign_id, business_date, window_days)
    );

CREATE TABLE IF NOT EXISTS resume_quality_reviews (
      id UUID PRIMARY KEY,
      resume_id TEXT NOT NULL,
      campaign_id TEXT NOT NULL,
      decision TEXT NOT NULL,
      note TEXT NOT NULL DEFAULT '',
      actor_id TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_campaign_org_status ON campaign_organizations(campaign_id, status);

CREATE INDEX IF NOT EXISTS idx_campaign_person_status ON campaign_people(campaign_id, status);

CREATE INDEX IF NOT EXISTS idx_evidence_entity ON evidence(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status, created_at);

CREATE INDEX IF NOT EXISTS idx_resumes_status ON resume_documents(status, updated_at);

CREATE INDEX IF NOT EXISTS idx_resume_identity_person ON resume_identity_matches(person_id, decision);

CREATE INDEX IF NOT EXISTS idx_employments_person ON employments(person_id, start_date);

CREATE INDEX IF NOT EXISTS idx_employments_org ON employments(organization_id, is_current);

CREATE INDEX IF NOT EXISTS idx_graph_from ON graph_edges(from_type, from_id, edge_type);

CREATE INDEX IF NOT EXISTS idx_graph_to ON graph_edges(to_type, to_id, edge_type);

CREATE INDEX IF NOT EXISTS idx_ai_runs_status ON ai_runs(status, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nightly_run_unique ON ai_runs(run_type, business_date) WHERE run_type = 'NIGHTLY' AND business_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_search_tasks_status ON search_tasks(status, priority DESC, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_search_feedback_task ON search_task_feedback(task_id);

CREATE INDEX IF NOT EXISTS idx_users_status ON users(status, email);

CREATE INDEX IF NOT EXISTS idx_web_sessions_user ON web_sessions(user_id, expires_at);

CREATE INDEX IF NOT EXISTS idx_activity_campaign_time ON activity_events(campaign_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_person_time ON activity_events(person_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_candidate_origins_person ON candidate_origins(campaign_id, person_id);

CREATE INDEX IF NOT EXISTS idx_strategy_campaign_status ON strategy_versions(campaign_id, status, version DESC);

CREATE INDEX IF NOT EXISTS idx_reviews_campaign_time ON review_runs(campaign_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_research_status ON research_tasks(status, created_at);

CREATE INDEX IF NOT EXISTS idx_claim_subject ON evidence_claims(subject_type, subject_id, status);

CREATE INDEX IF NOT EXISTS idx_projects_org ON projects(organization_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_campaign_window ON analytics_snapshots(campaign_id, window_days, business_date DESC);

CREATE INDEX IF NOT EXISTS idx_resume_quality_reviews_resume ON resume_quality_reviews(resume_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_candidate_origins_dedupe ON candidate_origins(dedupe_key);

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_campaign_organizations_campaign_id' AND conrelid = 'campaign_organizations'::regclass
  ) THEN
    ALTER TABLE campaign_organizations ADD CONSTRAINT fk_campaign_organizations_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_campaign_organizations_organization_id' AND conrelid = 'campaign_organizations'::regclass
  ) THEN
    ALTER TABLE campaign_organizations ADD CONSTRAINT fk_campaign_organizations_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_campaign_people_campaign_id' AND conrelid = 'campaign_people'::regclass
  ) THEN
    ALTER TABLE campaign_people ADD CONSTRAINT fk_campaign_people_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_campaign_people_person_id' AND conrelid = 'campaign_people'::regclass
  ) THEN
    ALTER TABLE campaign_people ADD CONSTRAINT fk_campaign_people_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_campaign_people_organization_id' AND conrelid = 'campaign_people'::regclass
  ) THEN
    ALTER TABLE campaign_people ADD CONSTRAINT fk_campaign_people_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE NO ACTION
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_tasks_campaign_id' AND conrelid = 'tasks'::regclass
  ) THEN
    ALTER TABLE tasks ADD CONSTRAINT fk_tasks_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_sources_campaign_id' AND conrelid = 'sources'::regclass
  ) THEN
    ALTER TABLE sources ADD CONSTRAINT fk_sources_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_feedback_campaign_id' AND conrelid = 'feedback'::regclass
  ) THEN
    ALTER TABLE feedback ADD CONSTRAINT fk_feedback_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_profile_versions_campaign_id' AND conrelid = 'profile_versions'::regclass
  ) THEN
    ALTER TABLE profile_versions ADD CONSTRAINT fk_profile_versions_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_documents_campaign_id' AND conrelid = 'resume_documents'::regclass
  ) THEN
    ALTER TABLE resume_documents ADD CONSTRAINT fk_resume_documents_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_documents_person_id' AND conrelid = 'resume_documents'::regclass
  ) THEN
    ALTER TABLE resume_documents ADD CONSTRAINT fk_resume_documents_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_documents_source_search_task_id' AND conrelid = 'resume_documents'::regclass
  ) THEN
    ALTER TABLE resume_documents ADD CONSTRAINT fk_resume_documents_source_search_task_id
      FOREIGN KEY (source_search_task_id) REFERENCES search_tasks(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_documents_source_strategy_version_id' AND conrelid = 'resume_documents'::regclass
  ) THEN
    ALTER TABLE resume_documents ADD CONSTRAINT fk_resume_documents_source_strategy_version_id
      FOREIGN KEY (source_strategy_version_id) REFERENCES strategy_versions(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_documents_experiment_assignment_id' AND conrelid = 'resume_documents'::regclass
  ) THEN
    ALTER TABLE resume_documents ADD CONSTRAINT fk_resume_documents_experiment_assignment_id
      FOREIGN KEY (experiment_assignment_id) REFERENCES experiment_assignments(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_identity_matches_resume_id' AND conrelid = 'resume_identity_matches'::regclass
  ) THEN
    ALTER TABLE resume_identity_matches ADD CONSTRAINT fk_resume_identity_matches_resume_id
      FOREIGN KEY (resume_id) REFERENCES resume_documents(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_identity_matches_person_id' AND conrelid = 'resume_identity_matches'::regclass
  ) THEN
    ALTER TABLE resume_identity_matches ADD CONSTRAINT fk_resume_identity_matches_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_identity_matches_matched_person_id' AND conrelid = 'resume_identity_matches'::regclass
  ) THEN
    ALTER TABLE resume_identity_matches ADD CONSTRAINT fk_resume_identity_matches_matched_person_id
      FOREIGN KEY (matched_person_id) REFERENCES people(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_employments_person_id' AND conrelid = 'employments'::regclass
  ) THEN
    ALTER TABLE employments ADD CONSTRAINT fk_employments_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_employments_organization_id' AND conrelid = 'employments'::regclass
  ) THEN
    ALTER TABLE employments ADD CONSTRAINT fk_employments_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE NO ACTION
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_employments_resume_id' AND conrelid = 'employments'::regclass
  ) THEN
    ALTER TABLE employments ADD CONSTRAINT fk_employments_resume_id
      FOREIGN KEY (resume_id) REFERENCES resume_documents(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_person_skills_person_id' AND conrelid = 'person_skills'::regclass
  ) THEN
    ALTER TABLE person_skills ADD CONSTRAINT fk_person_skills_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_person_skills_skill_id' AND conrelid = 'person_skills'::regclass
  ) THEN
    ALTER TABLE person_skills ADD CONSTRAINT fk_person_skills_skill_id
      FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE NO ACTION
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_person_skills_resume_id' AND conrelid = 'person_skills'::regclass
  ) THEN
    ALTER TABLE person_skills ADD CONSTRAINT fk_person_skills_resume_id
      FOREIGN KEY (resume_id) REFERENCES resume_documents(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_organization_facts_organization_id' AND conrelid = 'organization_facts'::regclass
  ) THEN
    ALTER TABLE organization_facts ADD CONSTRAINT fk_organization_facts_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_organization_facts_source_resume_id' AND conrelid = 'organization_facts'::regclass
  ) THEN
    ALTER TABLE organization_facts ADD CONSTRAINT fk_organization_facts_source_resume_id
      FOREIGN KEY (source_resume_id) REFERENCES resume_documents(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_graph_edges_source_resume_id' AND conrelid = 'graph_edges'::regclass
  ) THEN
    ALTER TABLE graph_edges ADD CONSTRAINT fk_graph_edges_source_resume_id
      FOREIGN KEY (source_resume_id) REFERENCES resume_documents(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_ai_runs_campaign_id' AND conrelid = 'ai_runs'::regclass
  ) THEN
    ALTER TABLE ai_runs ADD CONSTRAINT fk_ai_runs_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_ai_run_items_run_id' AND conrelid = 'ai_run_items'::regclass
  ) THEN
    ALTER TABLE ai_run_items ADD CONSTRAINT fk_ai_run_items_run_id
      FOREIGN KEY (run_id) REFERENCES ai_runs(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_search_tasks_campaign_id' AND conrelid = 'search_tasks'::regclass
  ) THEN
    ALTER TABLE search_tasks ADD CONSTRAINT fk_search_tasks_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_search_tasks_run_id' AND conrelid = 'search_tasks'::regclass
  ) THEN
    ALTER TABLE search_tasks ADD CONSTRAINT fk_search_tasks_run_id
      FOREIGN KEY (run_id) REFERENCES ai_runs(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_search_tasks_strategy_version_id' AND conrelid = 'search_tasks'::regclass
  ) THEN
    ALTER TABLE search_tasks ADD CONSTRAINT fk_search_tasks_strategy_version_id
      FOREIGN KEY (strategy_version_id) REFERENCES strategy_versions(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_search_tasks_experiment_assignment_id' AND conrelid = 'search_tasks'::regclass
  ) THEN
    ALTER TABLE search_tasks ADD CONSTRAINT fk_search_tasks_experiment_assignment_id
      FOREIGN KEY (experiment_assignment_id) REFERENCES experiment_assignments(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_search_task_feedback_task_id' AND conrelid = 'search_task_feedback'::regclass
  ) THEN
    ALTER TABLE search_task_feedback ADD CONSTRAINT fk_search_task_feedback_task_id
      FOREIGN KEY (task_id) REFERENCES search_tasks(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_learning_weights_campaign_id' AND conrelid = 'learning_weights'::regclass
  ) THEN
    ALTER TABLE learning_weights ADD CONSTRAINT fk_learning_weights_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_learning_recommendations_campaign_id' AND conrelid = 'learning_recommendations'::regclass
  ) THEN
    ALTER TABLE learning_recommendations ADD CONSTRAINT fk_learning_recommendations_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_learning_recommendations_run_id' AND conrelid = 'learning_recommendations'::regclass
  ) THEN
    ALTER TABLE learning_recommendations ADD CONSTRAINT fk_learning_recommendations_run_id
      FOREIGN KEY (run_id) REFERENCES ai_runs(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_user_roles_user_id' AND conrelid = 'user_roles'::regclass
  ) THEN
    ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_user_roles_role_id' AND conrelid = 'user_roles'::regclass
  ) THEN
    ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role_id
      FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_role_permissions_role_id' AND conrelid = 'role_permissions'::regclass
  ) THEN
    ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_role_id
      FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_role_permissions_permission_code' AND conrelid = 'role_permissions'::regclass
  ) THEN
    ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_permission_code
      FOREIGN KEY (permission_code) REFERENCES permissions(code) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_web_sessions_user_id' AND conrelid = 'web_sessions'::regclass
  ) THEN
    ALTER TABLE web_sessions ADD CONSTRAINT fk_web_sessions_user_id
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_strategy_versions_campaign_id' AND conrelid = 'strategy_versions'::regclass
  ) THEN
    ALTER TABLE strategy_versions ADD CONSTRAINT fk_strategy_versions_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_strategy_versions_parent_version_id' AND conrelid = 'strategy_versions'::regclass
  ) THEN
    ALTER TABLE strategy_versions ADD CONSTRAINT fk_strategy_versions_parent_version_id
      FOREIGN KEY (parent_version_id) REFERENCES strategy_versions(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_experiments_campaign_id' AND conrelid = 'experiments'::regclass
  ) THEN
    ALTER TABLE experiments ADD CONSTRAINT fk_experiments_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_experiments_strategy_version_id' AND conrelid = 'experiments'::regclass
  ) THEN
    ALTER TABLE experiments ADD CONSTRAINT fk_experiments_strategy_version_id
      FOREIGN KEY (strategy_version_id) REFERENCES strategy_versions(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_experiment_assignments_experiment_id' AND conrelid = 'experiment_assignments'::regclass
  ) THEN
    ALTER TABLE experiment_assignments ADD CONSTRAINT fk_experiment_assignments_experiment_id
      FOREIGN KEY (experiment_id) REFERENCES experiments(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_experiment_assignments_person_id' AND conrelid = 'experiment_assignments'::regclass
  ) THEN
    ALTER TABLE experiment_assignments ADD CONSTRAINT fk_experiment_assignments_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_review_runs_campaign_id' AND conrelid = 'review_runs'::regclass
  ) THEN
    ALTER TABLE review_runs ADD CONSTRAINT fk_review_runs_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_intelligence_sources_organization_id' AND conrelid = 'intelligence_sources'::regclass
  ) THEN
    ALTER TABLE intelligence_sources ADD CONSTRAINT fk_intelligence_sources_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_evidence_claims_organization_id' AND conrelid = 'evidence_claims'::regclass
  ) THEN
    ALTER TABLE evidence_claims ADD CONSTRAINT fk_evidence_claims_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_claim_sources_claim_id' AND conrelid = 'claim_sources'::regclass
  ) THEN
    ALTER TABLE claim_sources ADD CONSTRAINT fk_claim_sources_claim_id
      FOREIGN KEY (claim_id) REFERENCES evidence_claims(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_claim_sources_source_id' AND conrelid = 'claim_sources'::regclass
  ) THEN
    ALTER TABLE claim_sources ADD CONSTRAINT fk_claim_sources_source_id
      FOREIGN KEY (source_id) REFERENCES intelligence_sources(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_business_units_organization_id' AND conrelid = 'business_units'::regclass
  ) THEN
    ALTER TABLE business_units ADD CONSTRAINT fk_business_units_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_projects_organization_id' AND conrelid = 'projects'::regclass
  ) THEN
    ALTER TABLE projects ADD CONSTRAINT fk_projects_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_projects_business_unit_id' AND conrelid = 'projects'::regclass
  ) THEN
    ALTER TABLE projects ADD CONSTRAINT fk_projects_business_unit_id
      FOREIGN KEY (business_unit_id) REFERENCES business_units(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_project_claims_project_id' AND conrelid = 'project_claims'::regclass
  ) THEN
    ALTER TABLE project_claims ADD CONSTRAINT fk_project_claims_project_id
      FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_project_claims_claim_id' AND conrelid = 'project_claims'::regclass
  ) THEN
    ALTER TABLE project_claims ADD CONSTRAINT fk_project_claims_claim_id
      FOREIGN KEY (claim_id) REFERENCES evidence_claims(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_organization_events_organization_id' AND conrelid = 'organization_events'::regclass
  ) THEN
    ALTER TABLE organization_events ADD CONSTRAINT fk_organization_events_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_research_tasks_campaign_id' AND conrelid = 'research_tasks'::regclass
  ) THEN
    ALTER TABLE research_tasks ADD CONSTRAINT fk_research_tasks_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_research_tasks_organization_id' AND conrelid = 'research_tasks'::regclass
  ) THEN
    ALTER TABLE research_tasks ADD CONSTRAINT fk_research_tasks_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_campaign_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_person_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_organization_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_resume_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_resume_id
      FOREIGN KEY (resume_id) REFERENCES resume_documents(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_search_task_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_search_task_id
      FOREIGN KEY (search_task_id) REFERENCES search_tasks(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_strategy_version_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_strategy_version_id
      FOREIGN KEY (strategy_version_id) REFERENCES strategy_versions(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_activity_events_experiment_assignment_id' AND conrelid = 'activity_events'::regclass
  ) THEN
    ALTER TABLE activity_events ADD CONSTRAINT fk_activity_events_experiment_assignment_id
      FOREIGN KEY (experiment_assignment_id) REFERENCES experiment_assignments(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_campaign_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_person_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_person_id
      FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_resume_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_resume_id
      FOREIGN KEY (resume_id) REFERENCES resume_documents(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_search_task_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_search_task_id
      FOREIGN KEY (search_task_id) REFERENCES search_tasks(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_organization_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_organization_id
      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_strategy_version_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_strategy_version_id
      FOREIGN KEY (strategy_version_id) REFERENCES strategy_versions(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_candidate_origins_experiment_assignment_id' AND conrelid = 'candidate_origins'::regclass
  ) THEN
    ALTER TABLE candidate_origins ADD CONSTRAINT fk_candidate_origins_experiment_assignment_id
      FOREIGN KEY (experiment_assignment_id) REFERENCES experiment_assignments(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_analytics_snapshots_campaign_id' AND conrelid = 'analytics_snapshots'::regclass
  ) THEN
    ALTER TABLE analytics_snapshots ADD CONSTRAINT fk_analytics_snapshots_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_quality_reviews_resume_id' AND conrelid = 'resume_quality_reviews'::regclass
  ) THEN
    ALTER TABLE resume_quality_reviews ADD CONSTRAINT fk_resume_quality_reviews_resume_id
      FOREIGN KEY (resume_id) REFERENCES resume_documents(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_resume_quality_reviews_campaign_id' AND conrelid = 'resume_quality_reviews'::regclass
  ) THEN
    ALTER TABLE resume_quality_reviews ADD CONSTRAINT fk_resume_quality_reviews_campaign_id
      FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_strategy_versions_source_review_run_id' AND conrelid = 'strategy_versions'::regclass
  ) THEN
    ALTER TABLE strategy_versions ADD CONSTRAINT fk_strategy_versions_source_review_run_id
      FOREIGN KEY (source_review_run_id) REFERENCES review_runs(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_experiment_assignments_search_task_id' AND conrelid = 'experiment_assignments'::regclass
  ) THEN
    ALTER TABLE experiment_assignments ADD CONSTRAINT fk_experiment_assignments_search_task_id
      FOREIGN KEY (search_task_id) REFERENCES search_tasks(id) ON DELETE SET NULL
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;

CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

INSERT INTO schema_migrations (version) VALUES ('001_v2_initial') ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations (version) VALUES ('002_analytics_snapshots') ON CONFLICT DO NOTHING;
