import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";

const source = resolve(process.argv[2] || ".runtime/postgres-schema-source.db");
const output = resolve(process.argv[3] || "src/lib/postgres-schema.generated.ts");
const sqlOutput = resolve(process.argv[4] || "migrations/postgres/001_v2_initial.sql");
const db = new DatabaseSync(source, { readOnly: true });
const rows = db.prepare(`SELECT type, name, sql FROM sqlite_master
  WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND type IN ('table','index')
  ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, rowid`).all() as Array<{ type: string; name: string; sql: string }>;
db.close();

const uuidPrimaryTables = new Set([
  "strategy_versions", "experiments", "experiment_assignments", "review_runs", "intelligence_sources", "evidence_claims",
  "business_units", "projects", "organization_events", "research_tasks", "activity_events", "candidate_origins",
  "analytics_snapshots", "resume_quality_reviews",
]);
const uuidReferences = [
  "strategy_version_id", "parent_version_id", "source_review_run_id", "experiment_id", "experiment_assignment_id",
  "source_id", "claim_id", "business_unit_id", "project_id",
];

interface ForeignKeyDefinition {
  table: string;
  column: string;
  referencedTable: string;
  referencedColumn: string;
  onDelete: string;
}

const foreignKeys: ForeignKeyDefinition[] = [];

function extractForeignKeys(table: string, sql: string) {
  return sql.replace(/\b([a-z_]+)\s+([^,\n]+?)\s+REFERENCES\s+([a-z_]+)\(([a-z_]+)\)(?:\s+ON\s+DELETE\s+(CASCADE|SET NULL|RESTRICT|NO ACTION))?/gi,
    (_match, column: string, definition: string, referencedTable: string, referencedColumn: string, onDelete = "NO ACTION") => {
    foreignKeys.push({ table, column, referencedTable, referencedColumn, onDelete });
    const typedDefinition = uuidPrimaryTables.has(referencedTable)
      ? definition.replace(/\bTEXT\b/i, "UUID")
      : definition;
    return `${column} ${typedDefinition}`;
  });
}

function constraintSql(foreignKey: ForeignKeyDefinition) {
  const name = `fk_${foreignKey.table}_${foreignKey.column}`;
  return `DO $migration$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = '${name}' AND conrelid = '${foreignKey.table}'::regclass
  ) THEN
    ALTER TABLE ${foreignKey.table} ADD CONSTRAINT ${name}
      FOREIGN KEY (${foreignKey.column}) REFERENCES ${foreignKey.referencedTable}(${foreignKey.referencedColumn}) ON DELETE ${foreignKey.onDelete}
      DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $migration$;`;
}

function transform(row: (typeof rows)[number]) {
  let sql = row.sql.replace(/\s+COLLATE\s+NOCASE/gi, "");
  if (row.type === "table") {
    sql = extractForeignKeys(row.name, sql);
    sql = sql.replace(/^CREATE TABLE\s+/i, "CREATE TABLE IF NOT EXISTS ");
    if (uuidPrimaryTables.has(row.name)) sql = sql.replace(/\bid TEXT PRIMARY KEY\b/i, "id UUID PRIMARY KEY");
    for (const column of uuidReferences) sql = sql.replace(new RegExp(`\\b${column} TEXT\\b`, "g"), `${column} UUID`);
    sql = sql.replace(/\b([a-z_]+_json) TEXT\b/g, "$1 JSONB");
    sql = sql.replace(/\b([a-z_]+_at) TEXT\b/g, "$1 TIMESTAMPTZ");
    sql = sql.replace(/\b(window_start|window_end|valid_from|valid_until|retention_until) TEXT\b/g, "$1 TIMESTAMPTZ");
    if (row.name === "users") sql = sql.replace(/\bemail TEXT\b/, "email CITEXT");
    if (row.name === "roles") sql = sql.replace(/\bcode TEXT\b/, "code CITEXT");
  } else {
    sql = sql
      .replace(/^CREATE UNIQUE INDEX\s+/i, "CREATE UNIQUE INDEX IF NOT EXISTS ")
      .replace(/^CREATE INDEX\s+/i, "CREATE INDEX IF NOT EXISTS ");
  }
  return `${sql};`;
}

const objects = rows.map(transform);
foreignKeys.push(
  { table: "strategy_versions", column: "source_review_run_id", referencedTable: "review_runs", referencedColumn: "id", onDelete: "SET NULL" },
  { table: "experiment_assignments", column: "search_task_id", referencedTable: "search_tasks", referencedColumn: "id", onDelete: "SET NULL" },
);
const schema = [
  "SELECT pg_advisory_xact_lock(7268842401162020);",
  "CREATE EXTENSION IF NOT EXISTS citext;",
  ...objects,
  ...foreignKeys.map(constraintSql),
  "CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());",
  "INSERT INTO schema_migrations (version) VALUES ('001_v2_initial') ON CONFLICT DO NOTHING;",
  "INSERT INTO schema_migrations (version) VALUES ('002_analytics_snapshots') ON CONFLICT DO NOTHING;",
].join("\n\n");

mkdirSync(dirname(output), { recursive: true });
mkdirSync(dirname(sqlOutput), { recursive: true });
writeFileSync(output, `// Generated by scripts/generate-postgres-schema.ts.\nexport const POSTGRES_SCHEMA_SQL = ${JSON.stringify(schema)};\n`);
writeFileSync(sqlOutput, `-- Generated by scripts/generate-postgres-schema.ts.\n${schema}\n`);
console.log(`Generated ${output} and ${sqlOutput} from ${rows.length} SQLite schema objects.`);
